import {Model, type Relation} from '@nozbe/watermelondb';
import type {Associations} from '@nozbe/watermelondb/Model';
import {date, field, readonly, relation, text} from '@nozbe/watermelondb/decorators';

import {ExpenseSource, type ExpenseCategory} from '../enums';
import type Season from './Season';
import type StockTransaction from './StockTransaction';

/**
 * Khoản chi — a cost attributed to a season.
 *
 * Rows with `source = 'diary_auto'` are generated from supply consumption and
 * are READ-ONLY in the UI. Letting a farmer hand-edit a derived number would
 * make the generator and the stored value diverge with no way to reconcile
 * them at sync time (D7). `isEditable` below is what the form binds to.
 */
export default class Expense extends Model {
  static table = 'expenses';

  static associations: Associations = {
    seasons: {type: 'belongs_to', key: 'season_id'},
    stock_transactions: {type: 'belongs_to', key: 'stock_transaction_id'},
  };

  @text('season_id') seasonId!: string;
  @text('stock_transaction_id') stockTransactionId!: string | null;
  @text('category') category!: ExpenseCategory;
  @field('amount') amount!: number;
  @date('expense_date') expenseDate!: Date;
  @text('description') description!: string | null;
  @text('source') source!: ExpenseSource;

  @readonly @date('created_at') createdAt!: Date;
  @date('updated_at') updatedAt!: Date;

  @relation('seasons', 'season_id') season!: Relation<Season>;
  @relation('stock_transactions', 'stock_transaction_id')
  stockTransaction!: Relation<StockTransaction>;

  get isAutoGenerated(): boolean {
    return this.source === ExpenseSource.DIARY_AUTO;
  }

  get isEditable(): boolean {
    return !this.isAutoGenerated;
  }
}
