"""The shared sync contract — the file both codebases assert against.

`docs/sync_contract.json` lists, per synced table, exactly the columns that
cross the wire. This test regenerates it from the SQLAlchemy models and fails
if the committed file has drifted.

`mobile/src/db/__tests__/schema.test.ts` reads the SAME file and asserts the
WatermelonDB schema matches it. Two suites, in two languages, over one file.

Why bother: a field-name mismatch between the two schemas is the highest
probability cause of a silent sync bug in this project, and it is invisible
to both codebases individually — each one is internally consistent and
perfectly happy. The only way to catch it is to make the agreement itself a
committed artefact that both sides check.

Needs no database, so it runs in CI on every push (Issue #18).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.models import SYNC_MODELS, SYNC_TABLE_ORDER
from app.services.sync_service import SERVER_ONLY_COLUMNS, payload_columns

CONTRACT = Path(__file__).resolve().parents[2] / "docs" / "sync_contract.json"


def build_contract() -> dict:
    return {
        "_comment": (
            "Generated by backend/tests/test_sync_contract.py. Do not edit by hand. "
            "Lists the columns that cross the sync boundary, per table, in "
            "dependency order. mobile/src/db/schema.ts must match exactly."
        ),
        "schema_version": 1,
        "table_order": list(SYNC_TABLE_ORDER),
        "server_only_columns": sorted(SERVER_ONLY_COLUMNS),
        "tables": {
            table: sorted(payload_columns(model))
            for table, model in SYNC_MODELS.items()
        },
    }


class TestSyncContract:
    def test_matches_the_committed_contract(self):
        actual = build_contract()

        if not CONTRACT.exists():  # pragma: no cover - first run only
            CONTRACT.parent.mkdir(parents=True, exist_ok=True)
            CONTRACT.write_text(
                json.dumps(actual, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
            )
            pytest.skip(f"contract written to {CONTRACT}; re-run to assert")

        expected = json.loads(CONTRACT.read_text(encoding="utf-8"))
        assert actual == expected, (
            "The sync payload shape changed. If intended: delete "
            "docs/sync_contract.json, re-run to regenerate, then update "
            "mobile/src/db/schema.ts and add a WatermelonDB migration — or the "
            "two schemas will disagree and records will sync into nothing."
        )

    def test_server_only_columns_are_excluded_everywhere(self):
        for table, model in SYNC_MODELS.items():
            leaked = SERVER_ONLY_COLUMNS & set(payload_columns(model))
            assert not leaked, f"{table} leaks server-only columns: {leaked}"

    def test_generated_columns_are_excluded(self):
        """*_day_local are computed by PostgreSQL on write; a client sending
        one back would be rejected by the database."""
        for table, model in SYNC_MODELS.items():
            generated = {
                c.name for c in model.__table__.columns if c.computed is not None
            }
            assert not (generated & set(payload_columns(model))), (
                f"{table} exposes a generated column"
            )

    def test_every_table_carries_the_three_client_owned_columns(self):
        for table, model in SYNC_MODELS.items():
            cols = set(payload_columns(model))
            missing = {"id", "created_at", "updated_at"} - cols
            assert not missing, f"{table} is missing {missing} from its payload"

    def test_contract_covers_exactly_the_synced_tables(self):
        assert set(build_contract()["tables"]) == set(SYNC_TABLE_ORDER)
