/**
 * Thu chi theo mùa vụ (Issue #28).
 *
 * Summary first, then the two ledgers. The number a farmer opens this tab for
 * is "am I making money on this season?", and it should not require scrolling.
 *
 * Auto-generated expenses appear in the list — hiding them would make the
 * total look wrong — but carry a badge and no edit affordance. The farmer
 * needs to see WHERE the cost came from, which is exactly what makes the
 * automatic half trustworthy.
 */

import React, {useCallback, useEffect, useMemo, useState} from 'react';
import {
  ActivityIndicator,
  FlatList,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';

import SyncStatusBar from '../../components/SyncStatusBar';
import {database} from '../../db';
import {
  EXPENSE_CATEGORY_LABELS,
  ExpenseSource,
  SEASON_STATUS_LABELS,
} from '../../db/enums';
import type {Expense, Revenue, Season} from '../../db/models';
import {
  financeSummary,
  observeExpenses,
  observeRevenues,
  type FinanceSummary,
} from '../../services/finance';
import {observeSeasons} from '../../services/seasons';
import {colors, MIN_TOUCH_TARGET, radius, spacing, typography} from '../../theme';
import {formatDate} from '../../utils/date';
import {formatMoney, formatQuantity} from '../../utils/numeric';

type Tab = 'expenses' | 'revenues';

/**
 * One list renders both ledgers, so the rows need a discriminator. A bare
 * `Expense[] | Revenue[]` cannot be passed to FlatList — the element type
 * would be a union that neither row component accepts without a cast, and
 * casting here is exactly how the wrong row gets rendered for the wrong item.
 */
type LedgerItem =
  | {kind: 'expense'; id: string; expense: Expense}
  | {kind: 'revenue'; id: string; revenue: Revenue};

export interface FinanceScreenProps {
  onAddExpense?: (seasonId: string) => void;
  onAddRevenue?: (seasonId: string) => void;
  onEditExpense?: (expense: Expense) => void;
  onEditRevenue?: (revenue: Revenue) => void;
}

function SummaryCard({summary}: {summary: FinanceSummary}) {
  const profitable = summary.profit >= 0;

  return (
    <View style={styles.summary}>
      <View style={styles.summaryRow}>
        <View style={styles.summaryCell}>
          <Text style={styles.summaryLabel}>Doanh thu</Text>
          <Text style={[styles.summaryValue, styles.revenueColor]}>
            {formatMoney(summary.totalRevenue)}
          </Text>
        </View>
        <View style={styles.summaryCell}>
          <Text style={styles.summaryLabel}>Chi phí</Text>
          <Text style={[styles.summaryValue, styles.expenseColor]}>
            {formatMoney(summary.totalCost)}
          </Text>
        </View>
      </View>

      <View style={styles.profitBox}>
        <Text style={styles.profitLabel}>
          {profitable ? 'Lợi nhuận' : 'Đang lỗ'}
        </Text>
        <Text style={[styles.profitValue, !profitable && styles.lossColor]}>
          {formatMoney(summary.profit)}
        </Text>
        {summary.marginPct !== null && (
          <Text style={styles.marginText}>Biên {summary.marginPct}%</Text>
        )}
      </View>

      {summary.autoGeneratedCost > 0 && (
        <Text style={styles.splitText}>
          Trong đó {formatMoney(summary.autoGeneratedCost)} tự động từ nhật ký,{' '}
          {formatMoney(summary.manualCost)} nhập tay
        </Text>
      )}

      {summary.costByCategory.length > 0 && (
        <View style={styles.breakdown}>
          {summary.costByCategory.slice(0, 4).map(row => (
            <View key={row.category} style={styles.breakdownRow}>
              <Text style={styles.breakdownLabel}>
                {EXPENSE_CATEGORY_LABELS[row.category]}
              </Text>
              <View style={styles.barTrack}>
                <View style={[styles.barFill, {width: `${Math.max(row.sharePct, 2)}%`}]} />
              </View>
              <Text style={styles.breakdownValue}>{row.sharePct}%</Text>
            </View>
          ))}
        </View>
      )}
    </View>
  );
}

function ExpenseRow({expense, onPress}: {expense: Expense; onPress: () => void}) {
  const auto = expense.source === ExpenseSource.DIARY_AUTO;

  return (
    <TouchableOpacity
      style={styles.row}
      onPress={onPress}
      // Not disabled: tapping shows the read-only reason, which teaches the
      // rule. A dead row teaches nothing.
      accessibilityRole="button">
      <View style={styles.rowLeft}>
        <Text style={styles.rowTitle}>
          {EXPENSE_CATEGORY_LABELS[expense.category]}
          {auto ? '  🔗' : ''}
        </Text>
        <Text style={styles.rowMeta}>
          {formatDate(expense.expenseDate)}
          {expense.description ? ` · ${expense.description}` : ''}
        </Text>
        {auto && <Text style={styles.autoBadge}>Tự động từ nhật ký</Text>}
      </View>
      <Text style={[styles.rowAmount, styles.expenseColor]}>
        −{formatMoney(expense.amount)}
      </Text>
    </TouchableOpacity>
  );
}

function RevenueRow({revenue, onPress}: {revenue: Revenue; onPress: () => void}) {
  return (
    <TouchableOpacity style={styles.row} onPress={onPress} accessibilityRole="button">
      <View style={styles.rowLeft}>
        <Text style={styles.rowTitle}>{revenue.buyer || 'Bán nông sản'}</Text>
        <Text style={styles.rowMeta}>
          {formatDate(revenue.revenueDate)}
          {revenue.quantity !== null && revenue.unit
            ? ` · ${formatQuantity(revenue.quantity, revenue.unit)}`
            : ''}
          {revenue.unitPrice !== null ? ` × ${formatMoney(revenue.unitPrice)}` : ''}
        </Text>
      </View>
      <Text style={[styles.rowAmount, styles.revenueColor]}>
        +{formatMoney(revenue.amount)}
      </Text>
    </TouchableOpacity>
  );
}

export default function FinanceScreen({
  onAddExpense,
  onAddRevenue,
  onEditExpense,
  onEditRevenue,
}: FinanceScreenProps) {
  const [seasons, setSeasons] = useState<Season[]>([]);
  const [seasonId, setSeasonId] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>('expenses');
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [revenues, setRevenues] = useState<Revenue[]>([]);
  const [summary, setSummary] = useState<FinanceSummary | null>(null);

  useEffect(() => {
    const sub = observeSeasons(database).subscribe(rows => {
      setSeasons(rows);
      setSeasonId(current => current ?? rows[0]?.id ?? null);
    });
    return () => sub.unsubscribe();
  }, []);

  useEffect(() => {
    if (!seasonId) {
      setExpenses([]);
      setRevenues([]);
      setSummary(null);
      return;
    }
    const subs = [
      observeExpenses(database, seasonId).subscribe(setExpenses),
      observeRevenues(database, seasonId).subscribe(setRevenues),
    ];
    return () => subs.forEach(s => s.unsubscribe());
  }, [seasonId]);

  // Recomputed whenever either ledger changes, so the headline number can
  // never lag the rows below it.
  useEffect(() => {
    if (!seasonId) {
      return;
    }
    let cancelled = false;
    financeSummary(database, seasonId).then(next => {
      if (!cancelled) {
        setSummary(next);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [seasonId, expenses, revenues]);

  const items = useMemo<LedgerItem[]>(
    () =>
      tab === 'expenses'
        ? expenses.map(e => ({kind: 'expense' as const, id: e.id, expense: e}))
        : revenues.map(r => ({kind: 'revenue' as const, id: r.id, revenue: r})),
    [tab, expenses, revenues],
  );

  const handleAdd = useCallback(() => {
    if (!seasonId) {
      return;
    }
    if (tab === 'expenses') {
      onAddExpense?.(seasonId);
    } else {
      onAddRevenue?.(seasonId);
    }
  }, [seasonId, tab, onAddExpense, onAddRevenue]);

  if (seasons.length === 0) {
    return (
      <View style={styles.container}>
        <SyncStatusBar />
        <View style={styles.empty}>
          <Text style={styles.emptyIcon}>💰</Text>
          <Text style={styles.emptyTitle}>Chưa có mùa vụ nào</Text>
          <Text style={styles.emptyText}>
            Thu chi được tính theo từng mùa vụ. Tạo mùa vụ ở tab Nhật ký trước.
          </Text>
        </View>
      </View>
    );
  }

  const activeSeason = seasons.find(s => s.id === seasonId);

  return (
    <View style={styles.container}>
      <SyncStatusBar />

      {seasons.length > 1 && (
        <View style={styles.seasonPicker}>
          <FlatList
            horizontal
            data={seasons}
            keyExtractor={s => s.id}
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={styles.seasonPickerContent}
            renderItem={({item}) => (
              <TouchableOpacity
                style={[styles.seasonChip, seasonId === item.id && styles.seasonChipActive]}
                onPress={() => setSeasonId(item.id)}>
                <Text
                  style={[
                    styles.seasonChipText,
                    seasonId === item.id && styles.seasonChipTextActive,
                  ]}
                  numberOfLines={1}>
                  {item.name}
                </Text>
              </TouchableOpacity>
            )}
          />
        </View>
      )}

      {activeSeason && seasons.length === 1 && (
        <View style={styles.singleSeason}>
          <Text style={styles.singleSeasonName}>{activeSeason.name}</Text>
          <Text style={styles.singleSeasonMeta}>
            {activeSeason.cropType} · {SEASON_STATUS_LABELS[activeSeason.status]}
          </Text>
        </View>
      )}

      <FlatList<LedgerItem>
        data={items}
        keyExtractor={item => item.id}
        renderItem={({item}) =>
          item.kind === 'expense' ? (
            <ExpenseRow
              expense={item.expense}
              onPress={() => onEditExpense?.(item.expense)}
            />
          ) : (
            <RevenueRow
              revenue={item.revenue}
              onPress={() => onEditRevenue?.(item.revenue)}
            />
          )
        }
        ListHeaderComponent={
          <>
            {summary ? (
              <SummaryCard summary={summary} />
            ) : (
              <ActivityIndicator style={styles.loading} color={colors.primary} />
            )}

            <View style={styles.tabRow}>
              <TouchableOpacity
                style={[styles.tab, tab === 'expenses' && styles.tabActive]}
                onPress={() => setTab('expenses')}>
                <Text style={[styles.tabText, tab === 'expenses' && styles.tabTextActive]}>
                  Chi ({expenses.length})
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.tab, tab === 'revenues' && styles.tabActive]}
                onPress={() => setTab('revenues')}>
                <Text style={[styles.tabText, tab === 'revenues' && styles.tabTextActive]}>
                  Thu ({revenues.length})
                </Text>
              </TouchableOpacity>
            </View>
          </>
        }
        ListEmptyComponent={
          <Text style={styles.listEmptyText}>
            {tab === 'expenses'
              ? 'Chưa có khoản chi nào. Chi phí vật tư sẽ tự xuất hiện khi bạn ghi nhật ký.'
              : 'Chưa có khoản thu nào.'}
          </Text>
        }
        contentContainerStyle={styles.listContent}
        initialNumToRender={12}
        maxToRenderPerBatch={12}
        windowSize={7}
        removeClippedSubviews
      />

      <TouchableOpacity
        style={styles.fab}
        onPress={handleAdd}
        accessibilityRole="button"
        accessibilityLabel={tab === 'expenses' ? 'Thêm khoản chi' : 'Thêm khoản thu'}>
        <Text style={styles.fabText}>+</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  loading: {marginVertical: spacing.lg},

  seasonPicker: {backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border},
  seasonPickerContent: {padding: spacing.sm},
  seasonChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: spacing.xs,
    maxWidth: 200,
  },
  seasonChipActive: {backgroundColor: colors.primary, borderColor: colors.primary},
  seasonChipText: {...typography.caption, color: colors.textSecondary},
  seasonChipTextActive: {color: colors.textOnPrimary, fontWeight: '600'},

  singleSeason: {
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  singleSeasonName: {...typography.label, color: colors.text},
  singleSeasonMeta: {...typography.caption, color: colors.textSecondary},

  listContent: {padding: spacing.md, paddingBottom: 96},

  summary: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  summaryRow: {flexDirection: 'row'},
  summaryCell: {flex: 1},
  summaryLabel: {...typography.caption, color: colors.textSecondary},
  summaryValue: {...typography.heading, marginTop: 2},
  revenueColor: {color: colors.success},
  expenseColor: {color: colors.danger},
  lossColor: {color: colors.danger},

  profitBox: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    alignItems: 'center',
  },
  profitLabel: {...typography.caption, color: colors.textSecondary},
  profitValue: {...typography.title, fontSize: 26, color: colors.primaryDark},
  marginText: {...typography.caption, color: colors.textSecondary, marginTop: 2},

  splitText: {
    ...typography.caption,
    color: colors.textSecondary,
    marginTop: spacing.sm,
    textAlign: 'center',
  },

  breakdown: {marginTop: spacing.md},
  breakdownRow: {flexDirection: 'row', alignItems: 'center', marginBottom: spacing.xs},
  breakdownLabel: {...typography.caption, color: colors.textSecondary, width: 88},
  barTrack: {
    flex: 1,
    height: 8,
    backgroundColor: colors.border,
    borderRadius: 4,
    overflow: 'hidden',
    marginHorizontal: spacing.sm,
  },
  barFill: {height: 8, backgroundColor: colors.accent},
  breakdownValue: {...typography.caption, color: colors.textSecondary, width: 44, textAlign: 'right'},

  tabRow: {flexDirection: 'row', marginTop: spacing.md, marginBottom: spacing.sm},
  tab: {
    flex: 1,
    minHeight: MIN_TOUCH_TARGET,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: colors.border,
  },
  tabActive: {borderBottomColor: colors.primary},
  tabText: {...typography.label, color: colors.textSecondary},
  tabTextActive: {color: colors.primary},

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  rowLeft: {flex: 1},
  rowTitle: {...typography.label, color: colors.text},
  rowMeta: {...typography.caption, color: colors.textSecondary, marginTop: 2},
  autoBadge: {...typography.caption, color: colors.info, marginTop: 2},
  rowAmount: {...typography.heading},

  listEmptyText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.lg,
    lineHeight: 22,
  },

  empty: {flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.lg},
  emptyIcon: {fontSize: 56},
  emptyTitle: {...typography.title, color: colors.text, marginTop: spacing.md},
  emptyText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.sm,
    lineHeight: 22,
  },

  fab: {
    position: 'absolute',
    right: spacing.lg,
    bottom: spacing.lg,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  fabText: {fontSize: 32, color: colors.textOnPrimary, lineHeight: 36},
});
