"""Financial records, and the diary→expense generator (Issue #29).

The generator is the piece that means a farmer never types a cost twice: they
record "phun thuốc, 2 chai Regent" and the expense appears by itself.

Its correctness rests on one structural fact rather than on careful coding:

    UNIQUE (stock_transaction_id) WHERE stock_transaction_id IS NOT NULL

Exactly one expense can exist per stock movement. The database refuses a
second, so invariant I6 holds even against a buggy caller or a sync retry that
replays the same batch.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import select, update
from sqlalchemy.orm import Session

from app.core.timeutils import now_ms
from app.models import Expense, StockTransaction
from app.models.enums import ExpenseCategory, ExpenseSource, TxnType

UTC = timezone.utc


def sync_auto_expense(
    db: Session,
    txn: StockTransaction,
    *,
    season_id: str | None = None,
    device_id: str | None = None,
) -> Expense | None:
    """Create or update the `diary_auto` expense mirroring a stock movement.

    Idempotent by construction (invariant I4): called twice with the same
    transaction it converges on the same single row, because it looks the
    expense up by `stock_transaction_id` before deciding to insert.

    Returns None — writing nothing — when the movement should not produce an
    expense:

      * it is not an `out`. A stock-in is a purchase; the money leaves the
        household when the fertiliser is *bought*, and booking a cost again
        when it is used would count it twice.
      * it has no `diary_entry_id`. A bare stock-out from the inventory screen
        is a stock-take or a transfer, not new spending (invariant I7).
    """
    if txn.txn_type != TxnType.OUT.value or txn.diary_entry_id is None:
        return None

    effective_season = txn.season_id or season_id
    if effective_season is None:
        # expenses.season_id is NOT NULL: a cost that belongs to no season
        # cannot be reported on, and the whole point of the module is
        # per-season profit.
        return None

    existing = db.execute(
        select(Expense).where(Expense.stock_transaction_id == txn.id)
    ).scalar_one_or_none()

    ts = now_ms()

    if existing is not None:
        # Revive rather than insert: the unique index covers soft-deleted rows
        # too, so an entry that was deleted and then restored must reuse the
        # row it already has.
        existing.deleted_at = None
        existing.amount = txn.total_cost
        existing.expense_date = txn.txn_date
        existing.season_id = effective_season
        existing.category = ExpenseCategory.SUPPLY.value
        existing.source = ExpenseSource.DIARY_AUTO.value
        existing.updated_at = ts
        existing.last_device_id = device_id
        db.flush()
        return existing

    expense = Expense(
        id=str(uuid.uuid4()),
        household_id=txn.household_id,
        season_id=effective_season,
        stock_transaction_id=txn.id,
        category=ExpenseCategory.SUPPLY.value,
        amount=txn.total_cost,
        expense_date=txn.txn_date,
        description=None,
        source=ExpenseSource.DIARY_AUTO.value,
        created_at=ts,
        updated_at=ts,
        last_device_id=device_id,
    )
    db.add(expense)
    db.flush()
    return expense


def void_auto_expense(
    db: Session, txn_id: str, *, device_id: str | None = None
) -> bool:
    """Tombstone the expense generated by a movement. Returns True if one was live.

    Idempotent: voiding an already-void expense is success, not an error,
    because a sync retry will do exactly that.
    """
    result = db.execute(
        update(Expense)
        .where(
            Expense.stock_transaction_id == txn_id,
            Expense.deleted_at.is_(None),
        )
        .values(deleted_at=datetime.now(UTC), updated_at=now_ms(), last_device_id=device_id)
    )
    return (result.rowcount or 0) > 0


def season_totals(db: Session, household_id: uuid.UUID, season_id: str) -> dict:
    """Cost / revenue / profit for one season.

    `profit` is never stored. Storing it would need invalidation on every one
    of the many writes that can affect it, across two databases, one of which
    is frequently offline (invariant I10).

    Supply consumption is already present as `diary_auto` expenses, so there
    is no separate "add supply costs" step and double-counting is structurally
    impossible (invariant I9).
    """
    from decimal import Decimal

    from sqlalchemy import func

    from app.models import Revenue

    cost = db.execute(
        select(func.coalesce(func.sum(Expense.amount), 0)).where(
            Expense.household_id == household_id,
            Expense.season_id == season_id,
            Expense.deleted_at.is_(None),
        )
    ).scalar_one()

    revenue = db.execute(
        select(func.coalesce(func.sum(Revenue.amount), 0)).where(
            Revenue.household_id == household_id,
            Revenue.season_id == season_id,
            Revenue.deleted_at.is_(None),
        )
    ).scalar_one()

    cost = Decimal(cost)
    revenue = Decimal(revenue)
    return {
        "total_cost": cost,
        "total_revenue": revenue,
        "profit": revenue - cost,
    }
