/**
 * Thu chi (Issue #28).
 *
 * Two rules carry the weight here:
 *
 *   D7  a diary_auto expense is read-only — editing a derived value would
 *       make it diverge from its generator with no way to reconcile
 *   I9  supply cost reaches the season total exactly once
 */

import {Database} from '@nozbe/watermelondb';

import {ExpenseCategory, ExpenseSource, SupplyCategory, WorkType} from '../../db/enums';
import type {Expense, Revenue, Season, Supply} from '../../db/models';
// Static, not `await import()`: dynamic import fails under Jest's CJS VM
// with "A dynamic import callback was invoked without --experimental-vm-modules".
import {createDiaryEntry, deleteDiaryEntry, updateDiaryEntry} from '../diary';
import {
  createExpense,
  createRevenue,
  deleteExpense,
  financeSummary,
  resolveRevenueAmount,
  updateExpense,
  updateRevenue,
} from '../finance';
import {createSeason, ValidationError} from '../seasons';
import {recordStockIn} from '../stock';
import {createSupply} from '../supplies';
import {createTestDatabase} from './testDatabase';

let db: Database;
let season: Season;

const START = new Date('2026-12-01T03:00:00Z');

beforeEach(async () => {
  db = createTestDatabase();
  season = await createSeason(db, {
    name: 'Vụ Đông Xuân 2026',
    cropType: 'Lúa',
    startDate: START,
  });
});

async function seedAutoExpense(): Promise<{supply: Supply; expense: Expense}> {
  const supply = await createSupply(db, {
    name: 'Đạm Urê',
    category: SupplyCategory.FERTILIZER,
    unit: 'kg',
    unitCost: 12_000,
  });
  await recordStockIn(db, {supplyId: supply.id, quantity: 100});
  await createDiaryEntry(db, {
    seasonId: season.id,
    workType: WorkType.FERTILIZING,
    supplyUsages: [{supplyId: supply.id, quantity: 25}],
  });

  const expenses = await db.get<Expense>('expenses').query().fetch();
  const auto = expenses.find(e => e.source === ExpenseSource.DIARY_AUTO)!;
  return {supply, expense: auto};
}

// ═══════════════════════════════════════════════════════════════════════════
//  Chi phí thủ công
// ═══════════════════════════════════════════════════════════════════════════

describe('Khoản chi thủ công', () => {
  it('tạo với source = manual', async () => {
    const expense = await createExpense(db, {
      seasonId: season.id,
      category: ExpenseCategory.LABOR,
      amount: 1_500_000,
    });
    expect(expense.source).toBe(ExpenseSource.MANUAL);
    expect(expense.stockTransactionId).toBeNull();
    expect(expense.isEditable).toBe(true);
  });

  it('từ chối số tiền âm', async () => {
    await expect(
      createExpense(db, {
        seasonId: season.id,
        category: ExpenseCategory.LABOR,
        amount: -1,
      }),
    ).rejects.toThrow(ValidationError);
  });

  it('sửa và xoá được', async () => {
    const expense = await createExpense(db, {
      seasonId: season.id,
      category: ExpenseCategory.LABOR,
      amount: 100_000,
    });
    await updateExpense(db, expense.id, {amount: 250_000});

    const fresh = await db.get<Expense>('expenses').find(expense.id);
    expect(fresh.amount).toBe(250_000);

    await deleteExpense(db, expense.id);
    expect(await db.get<Expense>('expenses').query().fetchCount()).toBe(0);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  D7 — chi phí tự sinh là chỉ đọc
// ═══════════════════════════════════════════════════════════════════════════

describe('D7 — chi phí tự sinh chỉ đọc', () => {
  it('được gắn cờ không sửa được', async () => {
    const {expense} = await seedAutoExpense();
    expect(expense.amount).toBe(300_000);
    expect(expense.isAutoGenerated).toBe(true);
    expect(expense.isEditable).toBe(false);
  });

  it('sửa bị từ chối', async () => {
    const {expense} = await seedAutoExpense();
    await expect(updateExpense(db, expense.id, {amount: 1})).rejects.toThrow(
      'nhật ký canh tác',
    );
  });

  it('xoá bị từ chối', async () => {
    const {expense} = await seedAutoExpense();
    await expect(deleteExpense(db, expense.id)).rejects.toThrow(ValidationError);
  });

  it('số tiền không đổi sau lần sửa bị từ chối', async () => {
    const {expense} = await seedAutoExpense();
    await updateExpense(db, expense.id, {amount: 1}).catch(() => undefined);

    const fresh = await db.get<Expense>('expenses').find(expense.id);
    expect(fresh.amount).toBe(300_000);
  });

  it('sửa nhật ký thì chi phí đổi theo — đường hợp lệ duy nhất', async () => {
    const {supply, expense} = await seedAutoExpense();
    const entries = await db.get('diary_entries').query().fetch();

    await updateDiaryEntry(db, entries[0]!.id, {
      supplyUsages: [{supplyId: supply.id, quantity: 10}],
    });

    const fresh = await db.get<Expense>('expenses').find(expense.id);
    expect(fresh.amount).toBe(120_000);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  Doanh thu
// ═══════════════════════════════════════════════════════════════════════════

describe('resolveRevenueAmount', () => {
  it('tính từ sản lượng × đơn giá khi không có thành tiền', () => {
    expect(
      resolveRevenueAmount({seasonId: 's', quantity: 1250, unitPrice: 8500}),
    ).toBe(10_625_000);
  });

  it('thành tiền nhập tay luôn thắng phép nhân', () => {
    // Giao dịch thật hay bị làm tròn xuống, trừ hao độ ẩm, hoặc trả một phần.
    expect(
      resolveRevenueAmount({
        seasonId: 's',
        quantity: 1250,
        unitPrice: 8500,
        amount: 10_000_000,
      }),
    ).toBe(10_000_000);
  });

  it('thiếu cả hai thì báo lỗi', () => {
    expect(() => resolveRevenueAmount({seasonId: 's', quantity: 1250})).toThrow(
      ValidationError,
    );
  });

  it('từ chối số âm', () => {
    expect(() => resolveRevenueAmount({seasonId: 's', amount: -1})).toThrow(
      ValidationError,
    );
  });
});

describe('Khoản thu', () => {
  it('tạo và tính thành tiền', async () => {
    const revenue = await createRevenue(db, {
      seasonId: season.id,
      quantity: 1000,
      unit: 'kg',
      unitPrice: 8000,
    });
    expect(revenue.amount).toBe(8_000_000);
  });

  it('đổi đơn giá thì tính lại thành tiền', async () => {
    const revenue = await createRevenue(db, {
      seasonId: season.id,
      quantity: 1000,
      unit: 'kg',
      unitPrice: 8000,
    });
    await updateRevenue(db, revenue.id, {unitPrice: 9000});

    const fresh = await db.get<Revenue>('revenues').find(revenue.id);
    expect(fresh.amount).toBe(9_000_000);
  });

  it('thành tiền nhập tay không bị ghi đè', async () => {
    const revenue = await createRevenue(db, {
      seasonId: season.id,
      quantity: 1000,
      unit: 'kg',
      unitPrice: 8000,
    });
    await updateRevenue(db, revenue.id, {unitPrice: 9000, amount: 8_500_000});

    const fresh = await db.get<Revenue>('revenues').find(revenue.id);
    expect(fresh.amount).toBe(8_500_000);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  Tổng kết
// ═══════════════════════════════════════════════════════════════════════════

describe('financeSummary', () => {
  it('mùa vụ rỗng: biên lợi nhuận là null, không phải 0', async () => {
    const summary = await financeSummary(db, season.id);
    expect(summary.totalCost).toBe(0);
    expect(summary.profit).toBe(0);
    // "Chưa tính được" khác "bằng không" — đọc 0% nông dân sẽ tưởng hoà vốn.
    expect(summary.marginPct).toBeNull();
  });

  it('lợi nhuận = thu − chi', async () => {
    await createExpense(db, {
      seasonId: season.id,
      category: ExpenseCategory.LABOR,
      amount: 3_000_000,
    });
    await createRevenue(db, {seasonId: season.id, amount: 10_000_000});

    const summary = await financeSummary(db, season.id);
    expect(summary.profit).toBe(7_000_000);
    expect(summary.marginPct).toBe(70);
  });

  it('I9 — chi phí vật tư vào tổng đúng một lần', async () => {
    await seedAutoExpense();
    await createExpense(db, {
      seasonId: season.id,
      category: ExpenseCategory.LABOR,
      amount: 500_000,
    });

    const summary = await financeSummary(db, season.id);
    expect(summary.totalCost).toBe(800_000);
    expect(summary.autoGeneratedCost).toBe(300_000);
    expect(summary.manualCost).toBe(500_000);
    expect(summary.expenseCount).toBe(2);
  });

  it('phân tích theo nhóm, sắp xếp giảm dần', async () => {
    for (const [category, amount] of [
      [ExpenseCategory.LABOR, 600_000],
      [ExpenseCategory.TRANSPORT, 300_000],
      [ExpenseCategory.LABOR, 100_000],
    ] as const) {
      await createExpense(db, {seasonId: season.id, category, amount});
    }

    const summary = await financeSummary(db, season.id);
    expect(summary.costByCategory[0]!.category).toBe(ExpenseCategory.LABOR);
    expect(summary.costByCategory[0]!.amount).toBe(700_000);
    expect(summary.costByCategory[0]!.sharePct).toBe(70);
    expect(summary.costByCategory[1]!.sharePct).toBe(30);
  });

  it('xoá nhật ký thì tổng chi giảm theo', async () => {
    await seedAutoExpense();
    expect((await financeSummary(db, season.id)).totalCost).toBe(300_000);

    const entries = await db.get('diary_entries').query().fetch();
    await deleteDiaryEntry(db, entries[0]!.id);

    expect((await financeSummary(db, season.id)).totalCost).toBe(0);
  });
});
